apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabstir-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fabstir-db
  template:
    metadata:
      labels:
        app: fabstir-db
    spec:
      containers:
        - name: fabstir-db
          image: ammarhaiderak/fabstir-db:9c35f4320c51a496c822b762ee66892bb8a9f9d6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
          - configMapRef:
              name: fabstirdb-env
      nodeSelectors:
      - vke.vultr.com/node-pool: main