apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
  name: fabstir-db-lb
spec:
  type: LoadBalancer
  selector:
    app: fabstir-db
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001