apiVersion: v1
kind: Service
metadata:
  name: fabstir-db
spec:
  type: NodePort
  selector:
    app: fabstir-db
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
      nodePort: 31002