apiVersion: v1
kind: Service
metadata:
  name: transcoder
spec:
  type: NodePort
  selector:
    app: transcoder
  ports:
    - port: 80
      protocol: TCP
      targetPort: 50051
      nodePort: 31000