apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transcoder
  template:
    metadata:
      labels:
        app: transcoder
    spec:
      containers:
        - name: transcoder
          image: ammarhaiderak/fabstir-transcoder:604ac3b39a717bbceb7e0386debaed67fd7857bb
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 50051