apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "http"
  name: transcoder-lb
spec:
  type: LoadBalancer
  selector:
    app: transcoder
  ports:
    - port: 80
      protocol: TCP
      targetPort: 50051