apiVersion: v1
kind: Service
metadata:
  name: fabstir-snaps
spec:
  type: NodePort
  selector:
    app: fabstir-snaps
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
      nodePort: 31001